src/CaesHelp/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CaesHelp.Models;
using Microsoft.AspNetCore.Mvc;
using PaulMiami.AspNetCore.Mvc.Recaptcha;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CaesHelp.Controllers
{
    public class TestController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [ValidateRecaptcha]
        [HttpPost]
        public IActionResult Index(TestEmailNewsletterViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("ThankYou", new { name = viewModel.Name });
            }

            return View();
        }


        [HttpGet]
        public IActionResult JqueryValidationDisabled()
        {
            return View();
        }

        [ValidateRecaptcha]
        [HttpPost]
        public IActionResult JqueryValidationDisabled(TestEmailNewsletterViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction(nameof(ThankYou), new { name = viewModel.Name });
            }

            return View();
        }



        [HttpGet]
        public IActionResult ThankYou(string name)
        {
            return View(nameof(ThankYou), name);
        }
    }
}

src/CaesHelp/Views/Test/Index.cshtml
@using CaesHelp.Models
@model CaesHelp.Models.TestEmailNewsletterViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<form asp-controller="Test" asp-action="Index" method="post" class="form-horizontal">
    <h4>@ViewBag.Title</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <recaptcha />
            <span class="text-danger" id="recaptchaErrorMessage"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Signup</button>
        </div>
    </div>
</form>

@section Scripts {
    <recaptcha-script validation-message-element-id="recaptchaErrorMessage" />
}

src/CaesHelp/Views/Test/JqueryValidationDisabled.cshtml
@using CaesHelp.Models
@model CaesHelp.Models.TestEmailNewsletterViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<form asp-controller="Test" asp-action="JqueryValidationDisabled" method="post" class="form-horizontal">
    <h4>@ViewBag.Title</h4>
    <hr />
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <recaptcha />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Signup</button>
        </div>
    </div>
</form>

@section Scripts {
    <recaptcha-script jquery-validation="false" />
}

src/CaesHelp/Views/Test/ThankYou.cshtml
@{
    ViewBag.Title = "Successfully signed up for the newsletter";
}
@model string

<h4>@ViewBag.Title</h4>
<hr />
Thanks  @Model!