src/CaesHelp/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CaesHelp.Models
{
    public class Ticket
    {
        public virtual string FromEmail { get; set; }
        [Required(ErrorMessage = "You must select an Urgency Level")]
        public virtual string UrgencyLevel { get; set; }
        [Required(ErrorMessage = "You must select a Support Department")]
        public virtual string SupportDepartment { get; set; }
        public virtual string ForApplication { get; set; }
        public virtual string ForWebSite { get; set; }

        public virtual string YourPhoneNumber { get; set; }
        public virtual string LocationOfProblem { get; set; }
        [Required(ErrorMessage = "You must enter the Subject.")]
        //[DisplayName("Subject:")]
        public virtual string Subject { get; set; }
        [Required(ErrorMessage = "You must enter the Message Body.")]
        public virtual string MessageBody { get; set; }
        public virtual List<string> Availability { get; set; }
        public virtual List<string> EmailCCs { get; set; }
        public virtual ICollection<Attachment> Attachments { get; set; } //Note: if IList is used instead, a different mapping test is used.
    }
}

src/CaesHelp/Models/TicketViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Threading.Tasks;

namespace CaesHelp.Models
{


    public class TicketViewModel
    {
        public string AppName;
        public string CallingPage;
        public string PassedSubject;

        public List<string> Urgency { get; set; }
        public List<string> SupportDepartment { get; set; }
        public Ticket Ticket { get; set; }
        public List<string> ProgrammingSupportApps { get; set; }

        public Dictionary<string, string> AvailableApps { get; set; }

        public static TicketViewModel Create(string appName, string subject)
        {

            //Check.Require(ticketRepository != null, "ticketRepository is required.");            
            var viewModel = new TicketViewModel();
            viewModel.AppName = appName;
            viewModel.PassedSubject = subject;
            viewModel.Ticket = new Ticket();

            //This list isn't complete, but we haven't got a ticket from the missing ones in more that 2 years
            viewModel.AvailableApps = new Dictionary<string, string>();
            viewModel.AvailableApps.Add("", "-- Select a Program --");
            viewModel.AvailableApps.Add("ACE", "Academic Course Evaluations");
            viewModel.AvailableApps.Add("AD419", "AD419");
            viewModel.AvailableApps.Add("CatBert", "CatBert");
            viewModel.AvailableApps.Add("Commencement", "Commencement");
            viewModel.AvailableApps.Add("CRP", "Conference Registration And Payments");
            viewModel.AvailableApps.Add("EL", "Eligibility List");
            viewModel.AvailableApps.Add("ESRA", "Employee Salary Review Analysis");
            viewModel.AvailableApps.Add("GRAMPS", "Grants Management");
            viewModel.AvailableApps.Add("OPP", "PrePurchasing");
            viewModel.AvailableApps.Add("PTF", "PTF");
            viewModel.AvailableApps.Add("SIMS", "Student Information Management System");
            viewModel.AvailableApps.Add("STD", "Subject To Dismissal");




            viewModel.Urgency = new List<string>(5);
            viewModel.Urgency.Add("Non-Critical Issue");
            viewModel.Urgency.Add("Scheduled Requests");
            viewModel.Urgency.Add("Workaround Available");
            viewModel.Urgency.Add("Work Stoppage");
            viewModel.Urgency.Add("Critical");


            viewModel.SupportDepartment = new List<string>();
            if (string.IsNullOrEmpty(viewModel.AppName))
            {
                viewModel.SupportDepartment.Add("Computer Support");
                viewModel.SupportDepartment.Add("Web Site Support");
                viewModel.SupportDepartment.Add("Programming Support");
            }
            else
            {
                viewModel.SupportDepartment.Add("Programming Support");
                viewModel.Ticket.Subject = subject;
            }

            viewModel.ProgrammingSupportApps = new List<string>();
            if (viewModel.AvailableApps.Where(x => x.Key == viewModel.AppName).Any())
            {
                viewModel.ProgrammingSupportApps.Add(
                    viewModel.AvailableApps.Where(x => x.Key == viewModel.AppName).Single().Value);
                viewModel.Ticket.ForApplication = viewModel.ProgrammingSupportApps[0];
            }
            else
            {
                foreach (var application in viewModel.AvailableApps.OrderBy(a => a.Value))
                {
                    viewModel.ProgrammingSupportApps.Add(application.Value);
                }
            }
            return viewModel;
        }

    }

}

src/CaesHelp/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CaesHelp.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CaesHelp.Controllers
{
    public class TicketController : Controller
    {
        // GET: /<controller>/
        [HttpGet]
        public IActionResult RequestHelp(string appName, string subject)
        {
            if (!string.IsNullOrEmpty(appName))
            {
                if (appName.Contains("appName="))
                {
                    appName = appName.Substring(appName.LastIndexOf("appName=") + 8);
                }
            }
            if (!string.IsNullOrWhiteSpace(subject))
            {
                var subjectLength = (subject.Trim().Length - 1) / 2;
                if (subject[subjectLength] == ',')
                {
                    var subjectFirst = subject.Substring(0, subjectLength);
                    var subjectLast = subject.Substring(subjectLength + 1);
                    if (subjectFirst == subjectLast)
                    {
                        subject = subjectLast;
                    }
                }
            }



            return View(TicketViewModel.Create( appName, subject));
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RequestHelp(Ticket ticket)
        {
            var xxx = ticket;

            return this.RedirectToAction("RequestHelp");
        }

    }
}

src/CaesHelp/Views/Ticket/RequestHelp.cshtml
@using System.Security.Cryptography.X509Certificates
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model CaesHelp.Models.TicketViewModel

@{
    ViewBag.Title = "Request Help";
    Layout = "_Layout";
}

<h2>Request Help</h2>

@using (Html.BeginForm("RequestHelp", "Ticket"))
{
    <div>
        <div>
            <h2>Urgency Level</h2>
            <div>
                @Html.DropDownListFor(a => a.Ticket.UrgencyLevel, Model.Urgency.Select(x => new SelectListItem(){Text = x.ToString()} ),new{ @class="form-control"})
            </div>
        </div>
        <div>
            <h2>Support Department</h2>
            <div>
                @Html.DropDownListFor(a => a.Ticket.SupportDepartment, Model.SupportDepartment.Select(x => new SelectListItem() { Text = x.ToString() }), new { @class = "form-control" })
            </div>
        </div>
        
        <div>
            <h2>Your Phone Number</h2>
            <div>
                @Html.TextBoxFor(a => a.Ticket.YourPhoneNumber, new{ @class="form-control" })
            </div>
        </div>
        
        <div>
            <h2>Location</h2>
            <div>
                @Html.TextBoxFor(a => a.Ticket.LocationOfProblem, new { @class = "form-control" })
            </div>
        </div>
        
        <div>
            <h2>Web Site Address</h2>
            <div>
                @Html.TextBoxFor(a => a.Ticket.ForWebSite, new { @class = "form-control" })
            </div>
        </div>
        
        <div>
            <h2>For Application</h2>
            <div>
                @Html.DropDownListFor(a => a.Ticket.ForApplication, Model.AvailableApps.Select(x => new SelectListItem() { Text = x.Value, Value = x.Key}), new { @class = "form-control" })
            </div>
        </div>
        
        <div>
            <h2>Your Available Dates and Times</h2>
            <div>
                
            </div>
        </div>
        
        <div>
            <h2>Carbon Copies</h2>
            <div>
                
            </div>
        </div>
        
        <div>
            <h2>Add Attachment</h2>
            <div>

            </div>
        </div>
        
        <div>
            <h2>Subject</h2>
            <div>
                @Html.TextBoxFor(a => a.Ticket.Subject, new { @class = "form-control" })
            </div>
        </div>
        
        <div>
            <h2>MessageBody</h2>
            <div>
                @Html.TextAreaFor(a => a.Ticket.MessageBody, new { @class = "form-control" })
            </div>
        </div>
        <div>
            <button type="submit" class="btn">Send Ticket</button>
        </div>
    </div>
}

